language: node_js
node_js:
  - 10

cache: npm

branches:
  only:
    - master

install:
  - npm install
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN
  target_branch: master
  keep_history: true
  on:
    branch: master
